changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 📦 Other Changes
      labels:
        - '*'
      exclude:
        labels:
          - feature
          - enhancement
          - bug
          - fix
